// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq2mrV5Qi6fa-MwENf9iZ4yMtg9vj1_gI',
    appId: '1:350516041508:web:21724cd44c194ef9cb05b1',
    messagingSenderId: '350516041508',
    projectId: 'porcino-44a0f',
    authDomain: 'porcino-44a0f.firebaseapp.com',
    storageBucket: 'porcino-44a0f.appspot.com',
    measurementId: 'G-ZX4MZ5J2Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbNHzYbbOHiebDP5-Isp6I7T3xn6s2bs0',
    appId: '1:350516041508:android:d0dd2a64b64a9186cb05b1',
    messagingSenderId: '350516041508',
    projectId: 'porcino-44a0f',
    storageBucket: 'porcino-44a0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6syQlLS5SHYZsLVToApJ5bVIjAtV4QP0',
    appId: '1:350516041508:ios:07e851c2b4bf3996cb05b1',
    messagingSenderId: '350516041508',
    projectId: 'porcino-44a0f',
    storageBucket: 'porcino-44a0f.appspot.com',
    androidClientId: '350516041508-g44urfua26l70rdcc2ouelcv26bpe3de.apps.googleusercontent.com',
    iosClientId: '350516041508-11h270iqijk3jam63cutevkqfskgu4va.apps.googleusercontent.com',
    iosBundleId: 'com.example.porcicultura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6syQlLS5SHYZsLVToApJ5bVIjAtV4QP0',
    appId: '1:350516041508:ios:e33246bb24c7f8f2cb05b1',
    messagingSenderId: '350516041508',
    projectId: 'porcino-44a0f',
    storageBucket: 'porcino-44a0f.appspot.com',
    androidClientId: '350516041508-g44urfua26l70rdcc2ouelcv26bpe3de.apps.googleusercontent.com',
    iosClientId: '350516041508-p1us4vai72pep8afuub2nq2ta7s7tk7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.porcicultura.RunnerTests',
  );
}
